default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: storage/turbo-showcase-development.sqlite3
  cable:
    <<: *default
    database: storage/turbo-showcase-development-cable.sqlite3
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: storage/turbo-showcase-test.sqlite3
  cable:
    <<: *default
    database: storage/turbo-showcase-test-cable.sqlite3
    migrations_paths: db/cable_migrate

production:
  primary:
    <<: *default
    database: storage/turbo-showcase-production.sqlite3
  cable:
    <<: *default
    database: storage/turbo-showcase-production-cable.sqlite3
    migrations_paths: db/cable_migrate
